## **Create a pandas dataframe (DataFrame name as 'df') with numpy random values (4 features and 4 observation)**

In [10]:
import pandas as pd
import numpy as np
import random
alphabet = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'
data={
    'Matches':np.random.randint(0,200,size=4),
    'Runs Scored':np.random.randint(100,8000,size=4),
    'Average':np.random.uniform(0.0,100.0,4),
    'Central Contract':[random.choice(list(alphabet)) for _ in range(4)]
}
df=pd.DataFrame(data)
df

   Matches  Runs Scored    Average Central Contract
0       71         5889  51.460754                O
1      147         3879  78.306017                Z
2      118         4947  34.781112                F
3      160         6070  31.318215                T

# **Rename the task - 1 'df' dataframe column names to 'Random value 1', 'Random value 2', 'Random value 3' & 'Random value 4**

In [11]:
df.rename(columns={'Matches':'Random value 1','Runs Scored':'Random value 2','Average':'Random value 3','Central Contract':'Random value 4'},inplace=True)
df

   Random value 1  Random value 2  Random value 3 Random value 4
0              71            5889       51.460754              O
1             147            3879       78.306017              Z
2             118            4947       34.781112              F
3             160            6070       31.318215              T

# **Find the descriptive statistics of the 'df' dataframe.**

In [12]:
df.describe()

       Random value 1  Random value 2  Random value 3
count        4.000000        4.000000        4.000000
mean       124.000000     5196.250000       48.966524
std         39.454615     1006.746368       21.445402
min         71.000000     3879.000000       31.318215
25%        106.250000     4680.000000       33.915387
50%        132.500000     5418.000000       43.120933
75%        150.250000     5934.250000       58.172070
max        160.000000     6070.000000       78.306017

# **Check for the null values in 'df' and find the data type of the columns.**

In [14]:
df.isnull().any()

Random value 1    False
Random value 2    False
Random value 3    False
Random value 4    False
dtype: bool

In [18]:
data=df.dtypes
data

Random value 1      int64
Random value 2      int64
Random value 3    float64
Random value 4     object
dtype: object

# **Display the 'Random value 2' & 'Random value 3' columns with location method and index location method.**

In [19]:
df.loc[:,['Random value 2','Random value 3']]

   Random value 2  Random value 3
0            5889       51.460754
1            3879       78.306017
2            4947       34.781112
3            6070       31.318215

In [20]:
df.iloc[:,[1,2]]

   Random value 2  Random value 3
0            5889       51.460754
1            3879       78.306017
2            4947       34.781112
3            6070       31.318215